[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PHP Klarna"
authors = [{name = "vrajroham", email = "vaibhavraj@vrajroham.me"}]
dynamic = ["version", "description"]
